module.exports = [
  {
    type: 'input',
    name: 'name',
    message: 'Enter component name...',
  },
  {
    type: 'select',
    name: 'folder',
    message: 'Select screen folder...',
    choices: [
      'Auth',
      'CodeConfirm',
      'Start',
      'Main',
      'Profile',
      'Start',
      'Main',
      'ContactUs',
      'NotifScreen',
      'SearchResult',
      'Login',
      'Registration',
      'CodeConfirm',
      'MakeBowl',
      'Splash',
      'ProductDetail',
      'Order',
      'FoodMeasure',
      'DeliveryTerms',
      'Catcoins',
      //ADD MORE SCREENS
    ],
  },
];
